[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8b00ba2f2c147d44ca6545932b3370de251350c"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "50526c2527881f84acb25c7665e2af09808d57b869d38233d9a32029ba1ed53e"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc240db1f49bf483b8d24b32e9f42f96071f9d61"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "d9f3138a9615ad1b530b8bac757cab4d1d6d1a945aa6b6da0a9144cbd941a28d"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24b9fd96e97e8077902cfca1811bf90870b5a62a"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "c91fc46fa168690fc143f54aad231ef1cfe6f6004a2be26ef458fa3b7a6cde61"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.aarch64-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "245c1b38a9fac7f894154e856d44e830c0087b90"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "f4e65e2c2f5b15fa23fd4695f30160c9b027651914f09d032dc354c5aa538ee6"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.aarch64-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7f45386f3a39a31fdf02b349c241dc0b2641981"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "3333bdf9752eac3cee012c7ec39fcc0b6bcefdccd142837f511876c71d9113c1"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80522c35be22321191e7d3a8b1755b2700612745"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "3adf006372142ed5502959ad38d33132ea20e63ffffb464b5c8b2d977c07559c"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7fd2e73c70ddd8ba6f400a0b1a1ce6b720ccb9b"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "37ddc126a864530b2dd366f48b11292c7de8354f32b59c9fd08b1d47051e3de8"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73d4e124e73c908d65637c08c2fcd3bc266eec00"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "18ccfdac967c4e0d77b97fe96879c6d6c602d63e3f4aeb97eff70b5d985ea5c2"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e71307c1582afb53a3dd9191fa415e0b842c781"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "78f5fe8e3ed9c15eea3f933af638a2084c36f31afd79ab8ec58bb2da13e48ad6"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.i686-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9497d68ee60aa0ea3e0c75b07d29221afbc8b660"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "a9e72abd4a6c09b5459b4c61642f1a7cb3915f0c8b6e253e3f19d8f4fea4ede9"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.i686-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d60649afe38fa6a0d594fa50fba701118f559c40"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "9146186511c8d06a073029c3b6c5bb68d89191abfd5ddf64b35d58e13ae34683"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.i686-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b72e3f7c59bad2b235ddf09168d8bccfa80ab9a"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "7121106ca870bb2698f35bac69d55889c39d0e13979cd471cfb34e51875c84ff"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.i686-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "991bfc0602b3f20e29d665a710233d6f59be354e"
os = "windows"

    [[Xyce.download]]
    sha256 = "616d1edf3efe9c399cda7b1131fe1746bb3e07a19e31e8168550be16b152d36b"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.i686-w64-mingw32-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "884fc4139ebc33bd373973358c1e1b570297770b"
os = "windows"

    [[Xyce.download]]
    sha256 = "696852ac4f62eab8e9e032371a59b899f25d48a9e4f956178450042fe34ed3b4"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.i686-w64-mingw32-cxx11.tar.gz"
[[Xyce]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "600b688d424a1851d9f8b2752c470e18aa7f5762"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "26af1358622646ab8b4bf18594fb553d9f5206676a15bb86f7e1d60d03d401db"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58715272ac63363ef44b66340ce512214d464653"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "64e5ffc189cf992f5d2fb7778fd2ab7e44302f34f96b77c203b1591081f2876c"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
git-tree-sha1 = "cc27c5b5a4a4441beb0ecf57cff8190d92d1af1b"
os = "macos"

    [[Xyce.download]]
    sha256 = "eb37a87323f3a624ccf2d78b21e58dc3e9c7c55eb57d79372d586bb4994245a3"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.x86_64-apple-darwin.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9980473483d83c63c18a034f3d8fbb8447ed032e"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "43694562f2399019ec4b1e1a9652e4097bf40dacf57cb6c65b41c922210d895e"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa41df66b8c88dd1a2ff17a30badf441fc073fb1"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "6a2d904c3ade4eaf4a313b8f6fc7c23ea7b12cbbaa886cb66c7440141223e1c4"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24a43a2f61d515804038ffeced2ece2b284defe6"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "49c6d24cd76885dfb378de0997088834819da2de491a9825f94d32e6d9448fa7"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.x86_64-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b7ce39da6587231369fd9d77ec52be6c0e2de12"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "c145e91e967845f08d8277d924035174f0aeb415349c57c0e1113a9a60e15074"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.x86_64-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
git-tree-sha1 = "53da732982c362b33c35df2190c08c7ab1f793c1"
os = "freebsd"

    [[Xyce.download]]
    sha256 = "07b9144f108fc767cf424d481dd037256a59db2eca26c6aa3006022a22379bce"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.x86_64-unknown-freebsd.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f381df31fb508b6b255526af21ded1cf27039db"
os = "windows"

    [[Xyce.download]]
    sha256 = "fbdecae7d5904f1ff6f1f2c60cc2daca5af087f480a33aad01656e93db907461"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbb676f924589a0f0a3a3fbd4cf3bc59c23f7047"
os = "windows"

    [[Xyce.download]]
    sha256 = "3eaf443baf730b801ed2712abc91b3599ccdab56bf174842f1203716fb5c7775"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.3.1+1/Xyce.v7.3.1.x86_64-w64-mingw32-cxx11.tar.gz"
