[[Xyce]]
arch = "aarch64"
git-tree-sha1 = "df339115aa7dfcde86034af89cf61f29d9ba2660"
os = "macos"

    [[Xyce.download]]
    sha256 = "25c337cccabe8da875c67a509c50b8673f25ef2a520caa169ea79fd47ae620c2"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.aarch64-apple-darwin.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e66d00a5eb58646acc9dfca8cf6ec4fb49b62040"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "4f0bdd321cd4c40fb6bab8d73fb9c1ba846b156c3a313ef7b44898edb09692bf"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f841466bb36c65ecc0cf837c052e7b69c186fd6"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "d9c723af27d4cebbbf8c5279c7c368e53c90162940277fb14d0278e3d89e920d"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b694b9cfc939e672c262ca4f37c0044a2592c98a"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "131e6a98e24c6d637bca910837c768f778cb045972af596d6cec6ecc1f85e96b"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.aarch64-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dca26e7cb714d69637e4c0ab1764c47cc6f5c45d"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "151935d04bc1ac8825fdf254f1430f06ec81323239cb12da1029a74377bc619a"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "136e8d8de07b5587709c56024fef8fe416d1fb0a"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "e6dada8899d7e511a71968221c3623143c1d2adfef84d7f8ebf62ed5a0c0d2bc"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Xyce]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54eb237325e870afa48fa4594e654dd2720d8e5d"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "1188cc90db2c1c9be56f7a925c40bcc9cc0559bd020d9568e7a6ffda9b59a5a8"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Xyce]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef8dec0895c4422b95d572dc38945f16e755f8d1"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "3cce5a67c1956cc5df8664759f555722af104ce7047393cda4bc4405e39a78bc"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Xyce]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7d3007ef00739a45e77c306ccfd86e602449363"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "6cef6841a945ee3b958a4f9528ed52cf070b18b1fc71991a7eee277feedd6180"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62e55d9480c7fc363f2fc21370b58e58d35f3cf2"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "301e6ba14d88a75492ef0ffb1c295416489be48d8f702bb6d88de3c2c0dc61af"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09b46a293243bc14fa50c536d00ba3cc011c397c"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "ac44e6c37a4f054919667a483bd6c64f6f4bfc254ff2bf256d42501febe4eb6b"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15d747fb210a9b06b64720fded1cce039a726afc"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "b35aa24696db1b10c81b36e786bdec1f4755922eb58ba34222aa44161ad5ccfb"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40562bcf7139245d55340faeb642159a4a0cab74"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "b10250b0c0974fdb17649a6859b18ff77958c409d085ea0f83cfe04e35071677"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c2b157e5e0d1db1798917f86ac0f619e33ed5cb"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "be114d9c802a89b0acaaa9e0018827bd4e3c406296e36be483ddcc804150a059"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.i686-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af801473777f09fecdb203b9bbc3cae7aa8ebab8"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "850d68bd0e87d64354bf8ff0f8c6f1f884e04cc21f0fa47bce67fee975a9344b"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.i686-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fce7b5e3dcf9cd17ded4f54e41af2c889740a8d7"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "c743831819d96b715774df56e5be9a0c971a0a7858909de37e1b795b3f06784f"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.i686-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b250345ee870b80770ebf89e76f508631a43a33"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "d0cf8567825d5b21c3171ce19587589e458f4d19e8c357969f59850211413dbd"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.i686-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2af7288771335150ca702a4d20f7c21976961d0"
os = "windows"

    [[Xyce.download]]
    sha256 = "3686d1d99537add7e946d89e26352450fdcca24640f5b718fb0319ac9e7f09f4"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.i686-w64-mingw32-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22f1f1db1bf80e4e8a006efae833b03af2b3b132"
os = "windows"

    [[Xyce.download]]
    sha256 = "ba4dfabfab5b0fc79c71b7ead32509dc0905701a50745c3036fcb2787b14e970"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[Xyce]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca05a5256231c69d720c3cdbfb7519d30bea3556"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "4b1ed3dfd09cce99a4f424e1b33a7f162f5140bcbd3f9a1960b0deca350014a7"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6fe1db3af83c7f74bb73673814b5226a26d7d8c"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "8936da7acdfb829db9263794c934fb25c9b81ca3ce4814a3ac3c4116efd60c69"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
git-tree-sha1 = "9e738fa2c734c6d476ca46f9e67aeff5a2b32087"
os = "macos"

    [[Xyce.download]]
    sha256 = "7dbedec81a547dc30b22c51e6b0df7cd35d73ff40ddd5ba408526fc63c8e2bc8"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.x86_64-apple-darwin.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e87109d1fa324cb74fc233794a35dda6ec073f2"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "2c5ff15d122d2f91dbd2c2b2f9aa245ec021a3527353046d7a76ef5de2d45ba4"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb4529d9b9551b755bcdd6a0e2e5f3a74f644538"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "84daa3d6f6baee0973be6b260cefa0d702a5371806d09cdfa29a4f4c5c5f5266"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f7b7c972bc92856d13864de5e373e9822987fa9"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "44691cf8a335ace85ebe5646df3867f46639254b209398c4e4dcfc60bb4a5e19"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.x86_64-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3782b8ba49c15e9998ef3443b6c35025dcc7def1"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "eba39d118563fa1644f6c0209e8947a2233417a4be7bba42f1e4dba6ece84ed1"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
git-tree-sha1 = "a5ea2668e490dab44435fa47121fcbf6917ffc5f"
os = "freebsd"

    [[Xyce.download]]
    sha256 = "74907c4e88940f671373fd5386a5d0aa45efa739aabcc6dce46496f8983f6064"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.x86_64-unknown-freebsd.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb340aeb2cc31d5fae3468e01cac81e8bf777625"
os = "windows"

    [[Xyce.download]]
    sha256 = "032c113bbe0a29de8643a3dc242aa02259579f4c9e05b2a8215883ff8c8f8ac1"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb8d04300b693fab42c3f94315f33a3b292446f9"
os = "windows"

    [[Xyce.download]]
    sha256 = "9fac24857dc728e54cea8d5dcdd83514b2240dfb889cd54f380d7aa668570676"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.6.0+0/Xyce.v7.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
