[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6857ed213942c9847393dd13c977dabd84305e9d"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "07907c7c2e677ceab988ebff91621c936489bfc5291da33e5d5eea6e7e539d23"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.aarch64-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ebd16035b085c79244341a46f5555dc5ccf1a6a"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "3e5f2158fe40a3ba7258b8a451beec4187c19c27b813ebd275724118aadca140"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.aarch64-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9de914a80ec415a4c58d9dd1138ab95f5f5dd730"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "57b67665ab33d155aaa78e713ef5f7a230fc63e8cbfda4b2e4e7fdfadd96b4d9"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.aarch64-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "983024d3c794a461480bb819391e47ed40b06a9c"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "3f7075b5b6860bad915771e2abebff5e8d40436d188778bbbac4de1b422f1212"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.aarch64-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46f4996e6a19d3d0eb7da00542c93520baf561ec"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "8a07c4c6fcb3f3dc555835cfc3df605cbb8fa94135e3dfe668d7288dfa48bf7d"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87438062e66fbc41c2185635ac925ce2d1bccd23"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "af1b534fbd526d541c040f0bcdcb333fc2e6bab0eb9df647d4b2131c562d01fd"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9bb80a466dfcb700fb1a13fb361c3113f05d890"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "bd28f7aff609b1abfac922d49c0a30e880009ddfca5c2ddfc96a0912cd98582a"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83a070eb36e077ed46eedad9169bc9ac389cf409"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "a86ce6af87c9b5ec7ae1b4de32f59c81d40c6a71ab980f0326e20250c19a4c29"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37d2127a3161cdff50b1a0fd5ef93becfbfa41b5"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "64dfec295b8c5b66c68ab984861f34bffc19f2f38445226e81f2f47f90a7bfdc"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.i686-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b76f5365e11d400aea0a7c4fc16523dcc062b478"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "cdb1bc141300b5664178127c7302a1eed36d7e1933152ce49a0c12fa566f2d9a"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.i686-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c612f7af372dfb1360c78aa5d00ab1b913a50846"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "6fc554ab3fb23d3069929b38fb6470c85e58c3cf2b0acaafb38cbfde463c0e41"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.i686-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca7c67134a077a63fdf647665ce7e43deb46778b"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "e37fcee381387fba155d7d0e7090fa70e98c8e49ed5f5059dd3fb51b678383f0"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.i686-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eed3e3ea77fbab70f32f1aa7044dd33e18bbe985"
os = "windows"

    [[Xyce.download]]
    sha256 = "3a9faaaa01df7de4e9da48db526868f682046434a3d9eb399f5a5c8bde1d1220"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.i686-w64-mingw32-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39b11c87713cb8abfccff4cbced6548c44675643"
os = "windows"

    [[Xyce.download]]
    sha256 = "6c4e1a5e73c22c7aaaa57af7968d2f85fcc230dfa51eac28e1cd1e9a43c5cdee"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.i686-w64-mingw32-cxx11.tar.gz"
[[Xyce]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df4c7d526abc7730c38ee7196557317d0e7a4acd"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "ab6e85ab3377316b0c8760a10f97a6fb6eaf35ab07c6835bfb8d12a076dc6b79"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfd8ab0efd899b68250c622d4914d2707d767eb5"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "b8972ebcd51501c0469c43507d1a603b645ce583e6c3f71f72b86537b14ccb4c"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
git-tree-sha1 = "70c2d2b2c64cfbff27ddfc3d71333bebec7d0997"
os = "macos"

    [[Xyce.download]]
    sha256 = "757064c464124fb4056f92c9af2127ab5a1c91c8ac62bddb794398369623856f"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.x86_64-apple-darwin.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bc2ab904cea369fcf4dfaf565bfb940de3dcc23"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "4e4a7941305809071ecbbbb02306abc1f6e765ca1dc95708d965025f32b9f445"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.x86_64-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88e22a19ee7ca8a23daa2a34ad09b45f054c54d1"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "1c0b37a8951e554f2401067d2bda198a00af39333656d95710ee27ec81cfc3db"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.x86_64-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d535e7e514adf072ed0b97dbbf86b13cdc1a05cc"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "e0e70b7adac5a1cd0829e0723887ef1ee57de7e49d32cdc34f6843ae7b536312"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.x86_64-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc1ec01f98cf36e3786940f7d8bca1514380ef50"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "c6695d6de61635c71b771efef3b66123b0a667109a0710d53b5ed2a88dc76805"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.x86_64-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
git-tree-sha1 = "1da8b867e7946c1f972a02e9498d2c5df0706123"
os = "freebsd"

    [[Xyce.download]]
    sha256 = "c9f1af79492d70e4d36b4a78e9f7eae3db77c1456a44cd3e4b1d2e5bd4be3f71"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.x86_64-unknown-freebsd.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ba73305670ed1f0a7fb47bbcdf5c19a33d8c83b"
os = "windows"

    [[Xyce.download]]
    sha256 = "651df3b83d44c0469bf7edf555945b611bf2b9923033b49212cd4f028048ec28"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.x86_64-w64-mingw32-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e47ea0144d097e707aa9874eb92ff6c671e391c4"
os = "windows"

    [[Xyce.download]]
    sha256 = "9fd6037c632ab57b208610e124cf1c851197f02e6b7b132c96918d9e1f5783bb"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.99+0/Xyce.v7.4.99.x86_64-w64-mingw32-cxx11.tar.gz"
