[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "023b0ad912fdc1ee1bf6c4b145b5cc7e993d2763"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "b7a25b95383e456607547f9f818e80e02fd457421b22717366ebbdca495a3d53"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc8ccacc4845f99131513a6475de529d3057becb"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "2466c6fd80f424077ba23c144517c47c83edefedade6ccadcfc8a345531e2f6f"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e18b3c23f2d07e3cb0bfa4748b8e2d8036f0f49c"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "eb3c43be4b61a58aa9cb4c119e7d51916bff3171b11428f73bca04c27b0c6f6d"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c9297d0e67ff3e453f4a1a7a080ff47e54550c0"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "3b20c65ef60473cd2fd064899fcce8ef1d790670f25c743c34f05f1ce4a80682"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "481831809660d89c3388ae45dde78267a5362dfd"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "78ed644d8e838f7de0347c5eecbb43e16f36ce944295cf2bb252dc3e2b522574"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f421572d67366bf16b535d41a11ecdb6e7985636"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "b1b42a7b78c0c953e4ce00ff0e89f79e1e7fc75dbf0728e47ae6ca1968ad5c20"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd9eadc3f85c8a0ab256f653d78442a2316158fb"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "fa00373f722bbd647dd70e953fada601d265fe7e81e11f9c1e31ee41abe1142b"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Xyce]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bd41d07668423d00e4a5b304d15a7d928136549"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "755476afc19d2ed0f4192ad4018e4b7b5004a5dfaa980216abd324f3901b6dd0"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58e28c8863e2f5211ce59b5958ee5e1899c73f79"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "d55bbae94f5ef698c3441e17077e27ab53fd1a9f7f5c23eceff3fda51c8f094d"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.i686-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5aa8f35c063bc949d6111c9ca87b54a1696095fb"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "29198f61b13f0a679d83a0c17f347dd94a4cc961064be566e595abe9b47a9ba4"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.i686-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40dde53dded909d4d9ad3d472b7e0f37372762d5"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "7cef27dff3438e9de808da0dcd74d488a5d884a0073dd3d545240bf5bff5867f"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.i686-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "011601d216f5fcd7be8428e77c3daf10192f5cad"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "82b6f80a8e1ff0777420a67efaed8dccd3742f0287485b5e96838c93a9b05859"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.i686-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ef4c4fb939f060763cc0c7e9ba14618e953fec3"
os = "windows"

    [[Xyce.download]]
    sha256 = "569c2e477662a5c57f944282be9a1d96eede93ff660f56de1892d70d12f4d0c2"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[Xyce]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09e27c7b86ae26976ca98b9a2c64800bfd461924"
os = "windows"

    [[Xyce.download]]
    sha256 = "c55674a5e18b2df646dc1ed1291144937ddac4467a9566161a7afee1db5079f0"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[Xyce]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbe3d3b06c3c55bb00e272ce88fffe868e3ad9e0"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "a384c67bc485752deb128c121d5fc9290e8f17b1032a4e5b145d4c7603da5694"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9efede088f8fdbe545bba42a492384a17497c44c"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "24bb7bad50fb1348ab4beac872f0de5167552fa10139f20117a986c1ca7a0bd2"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
git-tree-sha1 = "eaa86b9f52d11890189de624742a24a98cf9ab29"
os = "macos"

    [[Xyce.download]]
    sha256 = "d00704f1779a06c5a2c5a73df613983b4081a5b95610693a11bfca364e230653"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.x86_64-apple-darwin.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8edc6776c18bd3f05537cd5abb17d39561e7b452"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "513b9b638708d4cf96b69df6b19213adbb5e634a9e5dabe8989f1150065bd8a3"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fce5567e5e6229af7b62c98379e2c20d922807ec"
libc = "glibc"
os = "linux"

    [[Xyce.download]]
    sha256 = "473a7be526e1650892d8762d1b3744ef749afa6bf3192dbf0d743b7492ccb0ff"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3972d0a65e27169cc807d90ce9bef6b9417728e"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "f69796e6b4e46dbb78ac4f8a68401b954508db6487eb8f05445cce5a9bde4ace"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c26934f63ecff7bfdff1f4759a0c53cf97a6e5f7"
libc = "musl"
os = "linux"

    [[Xyce.download]]
    sha256 = "7ce1f836bf0010550d752cadc6a25c4c9c9565571625dde1726a28ca3fcebfb1"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[Xyce]]
arch = "x86_64"
git-tree-sha1 = "48ada310d7b52791c7518dd4fe05698a40048ce8"
os = "freebsd"

    [[Xyce.download]]
    sha256 = "24a7ffcf19b40b30dc0187765b81ab1a60cf01dc71bab5358265cd99af8b619d"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.x86_64-unknown-freebsd.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1bc4c60565c1657cd43f5bbf2c7e373a60534af"
os = "windows"

    [[Xyce.download]]
    sha256 = "4bf2c2b20ea6fdda00ac2021dd33fefaf061212d1b65f52604412b05351b0a3f"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Xyce]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec906b27dd802169523e7f8aee68b1856f123b10"
os = "windows"

    [[Xyce.download]]
    sha256 = "f888337d1b072a39355bc112ab2ba701669538de17e6fc6da5c2a085e234399f"
    url = "https://github.com/JuliaBinaryWrappers/Xyce_jll.jl/releases/download/Xyce-v7.4.0+0/Xyce.v7.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
